package victor.testing.spring.repo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import victor.testing.spring.domain.Product;

public interface ProductRepo extends JpaRepository<Product, Long>, ProductRepoSearch { // ProductRepoSearch,

   @Query("SELECT p FROM Product p where p.name = ?1")
   Product findByName2(String name);

   //
//  autoGenerated @Query("SELECT p FROM Product p where p.supplier.name = ?1")
   Product findBySupplierName(String name);

//   Product fail(String name); fails startup
}
