-- -- create table email_to_send (id int8 not null, body varchar(255), recipient_email varchar(255), status varchar(255), subject varchar(255), version int8, primary key (id));
--
-- -- add one more column 'send_by' timestamp
-- ALTER TABLE email_to_send ADD COLUMN send_by timestamp;
--
-- -- set to the existing data a value of now + 1 week
-- -- UPDATE email_to_send SET send_by = now() + interval '1 week';
-- -- fails with Message    : Cannot parse "INTERVAL" constant "1 week"; SQL statement:
-- UPDATE email_to_send SET send_by = now() + interval '1 week';
--
-- -- make the column not null
-- ALTER TABLE email_to_send ALTER COLUMN send_by SET NOT NULL;